#!/bin/bash
DEVICE=`xinput list | grep 'Apple Internal Keyboard' | awk '{print $4}' | awk '{print substr($0, length($0) - 1, length($0))}'`
xinput set-int-prop $DEVICE "Device Enabled" 8 1
echo 'Internal keyboard enabled'
